name: film_riverpod_test
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-157.0.dev <4.0.0'

dependencies:
  collection: ^1.17.0
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  freezed_annotation: ^2.2.0
  go_router: ^7.0.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.1
  freezed: ^2.3.3
  json_serializable: ^6.6.2

flutter:
  uses-material-design: true
